# Generated by Django 2.1.4 on 2019-01-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'ordering': ['title'], 'verbose_name': 'Point of interest', 'verbose_name_plural': 'Points of interest'},
        ),
        migrations.RemoveField(
            model_name='poi',
            name='area',
        ),
        migrations.AddField(
            model_name='poi',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='poi',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
    ]
