# Generated by Django 2.1.4 on 2019-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190101_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
