# Generated by Django 2.1.4 on 2019-01-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_poi_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poi',
            old_name='location',
            new_name='city',
        ),
    ]
