# Generated by Django 2.1.4 on 2019-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190103_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
    ]
